# * *****************************************************************************
# * @ Encoding: UTF-8
# * @ File Name: Makefile
# * @ Author: carl
# * @ Created Time: 2021-10月-27(星期三) 00:54:01
# * @ All Rights Reserved
# * *****************************************************************************

test_model:
	g++ ../naughty_descent/naughty_descent.cpp ../naughty_descent/naughty_random_descent.cpp ../naughty_descent/model_base.cpp ../model_polyfit.cpp ./test.cc -I../naughty_descent -I.. -std=c++11
test_model_dbg:
	g++ ../naughty_descent/naughty_descent.cpp ../naughty_descent/naughty_random_descent.cpp ../naughty_descent/model_base.cpp ../model_polyfit.cpp ./test.cc -I../naughty_descent -I.. -std=c++11 -D_DEBUG
