# * *****************************************************************************
# * @ Encoding: UTF-8
# * @ File Name: Makefile
# * @ Author: carl
# * @ Created Time: 2021-10月-27(星期三) 00:54:01
# * @ SPDX-License-Identifier: Apache-2.0
# * *****************************************************************************

test_model:
	g++ ./test.cc -L.. -l:libnaughty_polyfit.a -I../naughty_descent -I.. -std=c++11
